# Generated by Django 3.1 on 2023-04-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='نام کوتاه')),
                ('image', models.ImageField(upload_to='media/', verbose_name='تصویر دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
