# Generated by Django 3.1 on 2023-05-13 23:17

import aboutus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 1 گالری'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 2 گالری'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 3 گالری'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery4',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 4 گالری'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery5',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 5 گالری'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 1 درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 2 درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='setting/', validators=[aboutus.models.validate_image_size], verbose_name=' تصویر 3 درباره ما'),
        ),
    ]
