# Generated by Django 3.1 on 2023-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('instagram', models.CharField(max_length=40, verbose_name='اینستاگرام')),
                ('whatsapp', models.CharField(max_length=40, verbose_name='واتساپ')),
                ('map_addres', models.CharField(max_length=350, verbose_name='آدرس نقشه')),
            ],
            options={
                'verbose_name': 'تنظیمات تماس  با ما',
                'verbose_name_plural': 'تنظیمات تماس با ما',
            },
        ),
    ]
