# Generated by Django 3.1 on 2023-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='instagram',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='map_addres',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='آدرس نقشه'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='واتساپ'),
        ),
    ]
