# Generated by Django 3.1 on 2023-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='نام مشتری')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(choices=[('آنلاین', 'آنلاین'), ('نقدی', 'نقدی')], default='آنلاین', max_length=20, verbose_name='نحوه پرداخت')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='سبد')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام میز')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='رزرو شده است')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('sub_total', models.IntegerField(verbose_name='مجموع')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem', verbose_name='آیتم سبد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.table', verbose_name='میز'),
        ),
    ]
