# Generated by Django 3.1 on 2023-04-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230416_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه سبد'),
        ),
    ]
