# Generated by Django 3.1 on 2023-04-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام آیتم')),
                ('slug', models.CharField(max_length=455, unique=True, verbose_name='نام کوتاه')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='تصویر آیتم')),
                ('materials', models.TextField(verbose_name='مواد تشکیل دهنده')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('is_available', models.BooleanField(default=True, verbose_name=',وضعیت موجودی')),
                ('description', models.TextField(verbose_name='توضحیات آیتم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'آیتم های منو',
            },
        ),
    ]
