# Generated by Django 3.1 on 2023-04-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='گالری 1'),
        ),
        migrations.AddField(
            model_name='menu',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='گالری 2'),
        ),
        migrations.AddField(
            model_name='menu',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='گالری 3'),
        ),
    ]
