# Generated by Django 3.1 on 2023-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230409_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='وضعیت موجودی'),
        ),
    ]
