# Generated by Django 3.1 on 2023-05-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
