# Generated by Django 3.1 on 2023-05-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20230508_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
