# Generated by Django 3.1 on 2023-05-09 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20230508_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان نظر'),
            preserve_default=False,
        ),
    ]
