# Generated by Django 3.1 on 2023-04-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabel', '0001_initial'),
        ('menu', '0003_auto_20230411_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='نام مشتری')),
                ('customer_number', models.CharField(max_length=25, verbose_name='شماره سفارش')),
                ('order_total', models.IntegerField(verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(choices=[('naghd', 'پرداخت نقدی'), ('online', 'پرداخت آنلاین')], default='آنلاین', max_length=20, verbose_name='نحوه پرداخت')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.table', verbose_name='میز')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('item_price', models.IntegerField(verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='آیتم منو')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
            },
        ),
    ]
