# Generated by Django 3.1 on 2023-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230417_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=0, verbose_name='مبلغ کل'),
        ),
    ]
